import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios';
import { useState } from 'react';
import UploadData from '../components/UploadData';
import GetData from '../components/GetData';
// import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div>
      <Head>
        <title>React Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <UploadData/>
    <GetData/>
    </div>
  )
}
